### ISSUE TITLE
Uncaught Error: Notification must be created with string message: Error: ENOENT: no such file or ...

### ISSUE THREAD

**Issue by mmnagueb** [ManRueda/jade-autocompile#14]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [jade-autocompile](https://github.com/ManRueda/jade-autocompile) package, v0.8.2
### Stack Trace

Uncaught Error: Notification must be created with string message: Error: ENOENT: no such file or directory, open 'E:\Work\NAGUEB\Personal\index.html
  doctype html'

```
At C:\Users\Mostafa\AppData\Local\atom\app-1.3.2\resources\app.asar\src\notification.js:25

Error: Notification must be created with string message: Error: ENOENT: no such file or directory, open 'E:\Work\NAGUEB\Personal\index.html
  doctype html'
    at Notification.module.exports.Notification.validate (C:\Users\Mostafa\AppData\Local\atom\app-1.3.2\resources\app.asar\src\notification.js:25:15)
    at new Notification (C:\Users\Mostafa\AppData\Local\atom\app-1.3.2\resources\app.asar\src\notification.js:20:12)
    at NotificationManager.module.exports.NotificationManager.addError (C:\Users\Mostafa\AppData\Local\atom\app-1.3.2\resources\app.asar\src\notification-manager.js:41:35)
    at writeFile (C:\Users\Mostafa\.atom\packages\jade-autocompile\lib\jade-autocompile.js:172:30)
    at fs.js:1149:21
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
  9x -1:15.4.0 core:move-right (atom-text-editor.editor.is-focused)
  6x -1:12.7.0 core:select-right (atom-text-editor.editor.is-focused)
     -1:08.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:59 tree-view:open-selected-entry-down (li.file.entry.list-item.selected)
     -0:37.9.0 tree-view:remove (span.name.icon.icon-file-text)
  2x -0:26 core:save (atom-text-editor.editor.is-focused)
     -0:19.8.0 tree-view:open-selected-entry-right (li.file.entry.list-item.selected)
     -0:15 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:14.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:14.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:14.8.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:13.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:12.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:07.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.3.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
jade-autocompile, v0.8.2
sass-autocompile, v0.12.2

# Dev
No dev packages
```

**Comment by manrueda** [comment]
With the last version the error should be fixed. If still doesn't work, please send me data about the folder structure of your project.
