### ISSUE TITLE
include not working 

### ISSUE THREAD

**Issue by ghost** [ManRueda/jade-autocompile#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [jade-autocompile](git+https://github.com/ManRueda/jade-autocompile) package, v0.6.2
### Stack Trace

Uncaught Error: Jade:3
    1| doctype html
    2| html

> 3|   include ./includes/head.jade
>     4|   body
>     5|     h1 My site
>     6|     

the "filename" option is required to use "include" with "relative" paths

```
At /Users/godric/.atom/packages/jade-autocompile/node_modules/jade/lib/runtime.js:240

Error: Jade:3
    1| doctype html
    2| html
  > 3|   include ./includes/head.jade
    4|   body
    5|     h1 My site
    6|     

the "filename" option is required to use "include" with "relative" paths
  at Parser.resolvePath (/Users/godric/.atom/packages/jade-autocompile/node_modules/jade/lib/parser.js:486:13)
  at Parser.parseInclude (/Users/godric/.atom/packages/jade-autocompile/node_modules/jade/lib/parser.js:585:21)
  at Parser.parseExpr (/Users/godric/.atom/packages/jade-autocompile/node_modules/jade/lib/parser.js:223:21)
  at Parser.block (/Users/godric/.atom/packages/jade-autocompile/node_modules/jade/lib/parser.js:729:25)
  at Parser.tag (/Users/godric/.atom/packages/jade-autocompile/node_modules/jade/lib/parser.js:838:24)
  at Parser.parseTag (/Users/godric/.atom/packages/jade-autocompile/node_modules/jade/lib/parser.js:759:17)
  at Parser.parseExpr (/Users/godric/.atom/packages/jade-autocompile/node_modules/jade/lib/parser.js:211:21)
  at Parser.parse (/Users/godric/.atom/packages/jade-autocompile/node_modules/jade/lib/parser.js:122:25)
  at parse (/Users/godric/.atom/packages/jade-autocompile/node_modules/jade/lib/index.js:104:21)
  at Object.exports.compile (/Users/godric/.atom/packages/jade-autocompile/node_modules/jade/lib/index.js:205:16)
  at handleTemplateCache (/Users/godric/.atom/packages/jade-autocompile/node_modules/jade/lib/index.js:174:25)
  at Object.exports.render (/Users/godric/.atom/packages/jade-autocompile/node_modules/jade/lib/index.js:349:10)
  at /Users/godric/.atom/packages/jade-autocompile/lib/jade-autocompile.js:122:25
  at Object.exports.allowUnsafeEval (/Users/godric/.atom/packages/jade-autocompile/node_modules/loophole/lib/loophole.js:14:14)
  at /Users/godric/.atom/packages/jade-autocompile/lib/jade-autocompile.js:121:27
  at Object.exports.allowUnsafeNewFunction (/Users/godric/.atom/packages/jade-autocompile/node_modules/loophole/lib/loophole.js:25:14)
  at readFile (/Users/godric/.atom/packages/jade-autocompile/lib/jade-autocompile.js:120:35)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```
### Commands

```
     -1:11.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:10.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:59.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:58.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:58.4.0 core:save (atom-text-editor.editor.is-focused)
  7x -0:50.1.0 core:move-right (atom-text-editor.editor.is-focused)
  8x -0:48.8.0 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:46.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:45.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:44.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:44 core:save (atom-text-editor.editor.is-focused)
  3x -0:35.6.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:20.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:07.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:07.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:01.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.8
atom-jade, v0.3.0
atom-material-syntax, v0.2.1
autocomplete-sass, v0.1.0
color-picker, v2.0.11
css-snippets, v0.8.0
emmet, v2.3.12
jade-autocompile, v0.6.2
language-jade, v0.5.1
pigments, v0.9.2
sass-autocompile, v0.7.3
sass-watch, v0.3.1

# Dev
No dev packages
```

![2015-07-28 11 43 22](https://cloud.githubusercontent.com/assets/12566504/8927154/12403d7c-351e-11e5-83bf-109aa6a16d32.png)

**Comment by manrueda** [comment]
The bug was fixed and the new release it's on APM
