### ISSUE TITLE
Failed to load the jade-autocompile package

### ISSUE THREAD

**Issue by MikSDigital** [ManRueda/jade-autocompile#5]
[Enter steps to reproduce below:]
1. just after fresh installation on Windows 7
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [jade-autocompile](https://github.com/ManRueda/jade-autocompile) package, v0.6.3
### Stack Trace

Failed to load the jade-autocompile package

```
At Cannot find module 'loophole'

Error: Cannot find module 'loophole'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Михаил\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at C:\Users\Михаил\.atom\packages\jade-autocompile\lib\jade-autocompile.js:6:18
  at Object.<anonymous> (C:\Users\Михаил\.atom\packages\jade-autocompile\lib\jade-autocompile.js:173:3)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\Михаил\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Михаил\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:761:34)
  at C:\Users\Михаил\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:192:28
  at Package.module.exports.Package.measure (C:\Users\Михаил\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.load (C:\Users\Михаил\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:183:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Михаил\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Михаил\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:485:30)
  at C:\Users\Михаил\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:313:60
  at exit (C:\Users\Михаил\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\Михаил\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:213:47)
  at C:\Users\Михаил\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:220:18
  at Socket.<anonymous> (C:\Users\Михаил\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
  4x -5:41.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:33.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  9x -5:32.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-jade, v0.3.0
jade-autocompile, v0.6.3
language-jade, v0.6.2

# Dev
No dev packages
```

**Comment by manrueda** [comment]
Hi, have you try to re-install the package? I did a fresh install in a Windows 7 and everything work great...

**Comment by MikSDigital** [comment]
Hi!

Thanks for such a quick reply!

Yes, now seems everything ok.

Thank you!

**Comment by manrueda** [comment]
Great!! Closing bug...

Thanks

**Comment by phillyDesignr** [comment]
Hi,
I've uninstalled and reinstalled several times but still get this error:

`[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [jade-autocompile](https://github.com/ManRueda/jade-autocompile) package, v0.8.3


### Stack Trace

Failed to load the jade-autocompile package

```
At C:\Users\foobar\.atom\packages\jade-autocompile\lib\jade-autocompile.js:173
        then: (_fn) =>{
                    ^^
Unexpected token =>

C:\Users\foobar\.atom\packages\jade-autocompile\lib\jade-autocompile.js:173
        then: (_fn) =>{
                    ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:411:25)
    at Object.defineProperty.value [as .js] (C:\Users\foobar\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\foobar\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:761:34)
    at C:\Users\foobar\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:192:28
    at Package.module.exports.Package.measure (C:\Users\foobar\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:169:15)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
jade-autocompile, v0.8.3
sass-autocompile, v0.12.3

# Dev
No dev packages
```

`
