### ISSUE TITLE
Uncaught SyntaxError: Unexpected token (1:11)

### ISSUE THREAD

**Issue by krotovic** [ManRueda/jade-autocompile#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Ubuntu 14.04.3
**Thrown From**: [jade-autocompile](https://github.com/ManRueda/jade-autocompile) package, v0.6.3
### Stack Trace

Uncaught SyntaxError: Unexpected token (1:11)

```
At /home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1747

SyntaxError: Unexpected token (1:11)
  at Parser.pp.raise (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1745:13)
  at Parser.pp.unexpected (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2264:8)
  at Parser.pp.parseBindingAtom (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1876:12)
  at Parser.pp.parseMaybeDefault (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1920:23)
  at Parser.pp.parseBindingList (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1896:23)
  at Parser.pp.parseFunctionParams (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2776:22)
  at Parser.pp.parseFunction (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2769:8)
  at Parser.pp.parseExprAtom (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1129:19)
  at Parser.pp.parseExprSubscripts (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1023:19)
  at Parser.pp.parseMaybeUnary (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1004:19)
  at Parser.pp.parseExprOps (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:948:19)
  at Parser.pp.parseMaybeConditional (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:930:19)
  at Parser.pp.parseMaybeAssign (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:908:19)
  at Parser.pp.parseParenAndDistinguishExpression (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1188:28)
  at Parser.pp.parseExprAtom (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1111:19)
  at Parser.pp.parseExprSubscripts (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1023:19)
  at Parser.pp.parseMaybeUnary (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1004:19)
  at Parser.pp.parseExprOps (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:948:19)
  at Parser.pp.parseMaybeConditional (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:930:19)
  at Parser.pp.parseMaybeAssign (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:908:19)
  at Parser.pp.parseExpression (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:882:19)
  at Parser.pp.parseStatement (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2461:23)
  at Parser.pp.parseTopLevel (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2379:21)
  at Object.parse (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:101:12)
  at reallyParse (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/index.js:24:18)
  at unwrapReturns (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/index.js:90:13)
  at addWith (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/node_modules/with/index.js:77:37)
  at parse (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/lib/index.js:149:9)
  at Object.exports.compile (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/lib/index.js:205:16)
  at handleTemplateCache (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/lib/index.js:174:25)
  at Object.exports.render (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/jade/lib/index.js:349:10)
  at /home/krotovicl/.atom/packages/jade-autocompile/lib/jade-autocompile.js:129:25
  at Object.exports.allowUnsafeEval (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/loophole/lib/loophole.js:14:14)
  at /home/krotovicl/.atom/packages/jade-autocompile/lib/jade-autocompile.js:128:27
  at Object.exports.allowUnsafeNewFunction (/home/krotovicl/.atom/packages/jade-autocompile/node_modules/loophole/lib/loophole.js:25:14)
  at readFile (/home/krotovicl/.atom/packages/jade-autocompile/lib/jade-autocompile.js:127:35)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

```
### Commands

```
     -0:13.2.0 core:save (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "projectHome": "/home/krotovicl/Workspace",
    "themes": [
      "nucleus-dark-ui",
      "batman-syntax"
    ],
    "disabledPackages": [
      "markdown-preview",
      "autocomplete-css"
    ],
    "packagesWithKeymapsDisabled": [
      "build-npm-apm"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
angularjs, v0.3.3
atom-beautify, v0.28.16
atom-jade, v0.3.0
atom-jasmine, v0.6.0
atom-typescript, v7.7.0
autocomplete-modules, v1.3.1
batman-syntax, v1.0.1
bower-install, v0.2.4
build, v0.48.0
build-gulp, v0.2.0
build-npm-apm, v0.2.0
color-picker, v2.0.13
emmet, v2.3.13
gulp-snippets, v0.6.2
jade-autocompile, v0.6.3
language-docker, v1.1.3
language-nginx, v0.6.1
language-svg, v0.9.0
less-autocompile, v1.0.0
linter, v1.10.0
markdown-preview-plus, v2.2.2
mathjax-wrapper, v0.1.0
nucleus-dark-ui, v0.6.6
pigments, v0.18.1
project-manager, v2.6.5
sass-autocompile, v0.10.7
svg-preview, v0.6.1
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by manrueda** [comment]
Hi @krotovic, can you send me the jade code that you are trying to compile? My tests run ok in atom 1.1.0

**Comment by krotovic** [comment]
Well, I don't already have that file, so nevermind this issue.
