### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by tofagerl** [ManRueda/jade-autocompile#7]
1. Write jade
2. Save file

```
//- mixin type(elementType, type, value, label)
//-   if(elementType == type)
//-     option(value='#{value}', label='#{label}', selected='selected') #{label}
//-   else
//-     option(value='#{value}', label='#{label}') #{label}
//-     
mixin owner(role, element)
  if(element.get('type') == 'Entity')
    if(role.get('source') == element.get('id'))
      option(value='#{element.id}', label='#{element.get("name")}', selected='selected') #{element.get('name')}
    else
      option(value='#{element.id}', label='#{element.get("name")}') #{element.get('name')}

mixin role(selectedElement, elements)
  if(selectedElement.type == 'Role')
    #ownerLabel.col-sm-4
      label(form='editElement') Owner:
    #ownerSelect.col-sm-8
      select(form='editElement', name='owner')
        each element in elements
          +owner(selectedElement, element)
.row#editElement
  form(name='editElement')
    input(form='editElement', type='hidden', name='elementId', value='#{selectedElement.get("id")}')
    label(form="editElement") Name:
    input(form="editElement", name='name', type='text', value="#{selectedElement.get('name')}")
    button#saveElement.btn.btn-primary(type="button", onclick='controller.saveElement(selectedElement.get("id"))') Save
    button#cancelElement.btn.btn-warning(type='button', onclick='controller.emptyToolbox()') Cancel
    +role(selectedElement, elements)

```

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [jade-autocompile](https://github.com/ManRueda/jade-autocompile) package, v0.6.4
### Stack Trace

Uncaught TypeError: Cannot read property 'trim' of undefined

```
At /Users/tom/.atom/packages/jade-autocompile/lib/jade-autocompile.js:27

TypeError: Cannot read property 'trim' of undefined
  at getOptions (/Users/tom/.atom/packages/jade-autocompile/lib/jade-autocompile.js:27:42)
  at readFile (/Users/tom/.atom/packages/jade-autocompile/lib/jade-autocompile.js:114:16)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

```
### Commands

```
  2x -3:36.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:34.2.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
 19x -3:32.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -2:39.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:35 editor:newline (atom-text-editor.editor.is-focused)
     -2:22.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:19.6.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:12.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:48.9.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:39.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:37 core:move-right (atom-text-editor.editor.is-focused)
     -1:34.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:55.6.0 editor:newline (atom-text-editor.editor.is-focused)
  8x -0:52.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:09.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:06.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-make",
      "language-clojure",
      "language-go",
      "language-perl",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "package-generator",
      "welcome",
      "atom-coffee-repl",
      "wrap-guide",
      "linter-coffeescript",
      "vim-mode",
      "minimap",
      "swackets"
    ],
    "ignoredNames": [
      ".DS_Store",
      ".git"
    ],
    "audioBeep": false,
    "projectHome": "/Users/tom/dev",
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "isotope-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.16
atom-jade, v0.3.0
atom-ternjs, v0.8.4
colorful-json, v1.0.0
editorconfig, v1.2.2
esformatter, v1.16.0
fetch, v0.3.0
highlight-line, v0.11.0
isotope-ui, v2.7.0
jade-autocompile, v0.6.4
jsonlint, v1.1.2
language-babel, v1.0.0
language-docker, v1.1.3
language-jade, v0.6.2
language-viml, v0.2.0
linter, v1.10.0
linter-eslint, v4.0.0
linter-jsonlint, v1.0.1
pigments, v0.18.1
pretty-json, v0.4.1
react, v0.12.10
tool-bar, v0.1.9

# Dev
bracket-matcher, v0.76.0
```

**Comment by manrueda** [comment]
Hi @tofagerl, 
I just detect the problem with the mixin syntax. Tonight i will fix it and publish an update

**Comment by manrueda** [comment]
Try with the last version. This new version ignore the //- comment for the config. 
Anyway, i can't compile your code in the native jade compiler. I think there is an error with the mixins

**Comment by tofagerl** [comment]
I'll try it monday. The code works fine here: http://jade-lang.com/demo/

**Comment by tofagerl** [comment]
Yep, works fine now! Thanks :)

**Comment by BackSpaceTech** [comment]
This still occurs if you leave out the //output: comment, for example in a jade file that doesn't need to be compiled that is an include to another file. Any comments at the start of the file will throw the same error. No comments at the start of the file doesn't throw the error. Would be good if we could have comments at the start of our include files to describe them without throwing the error.
