### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by Brwinded** [ManRueda/jade-autocompile#8]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.0-beta5
**System**: Unknown Windows Version
**Thrown From**: [jade-autocompile](https://github.com/ManRueda/jade-autocompile) package, v0.6.5
### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of null

```
At C:\Users\Brwin\AppData\Local\atom\app-1.3.0-beta5\resources\app.asar\src\pane.js:829

TypeError: Cannot read property 'classList' of null
    at IconView.setNoCompiled (C:\Users\Brwin\.atom\packages\jade-autocompile\lib\jade-autocompile-view.js:67:7)
    at Object.compile (C:\Users\Brwin\.atom\packages\jade-autocompile\lib\jade-autocompile.js:105:20)
    at Object.handleSave (C:\Users\Brwin\.atom\packages\jade-autocompile\lib\jade-autocompile.js:98:17)
    at C:\Users\Brwin\.atom\packages\jade-autocompile\lib\jade-autocompile.js:162:17
    at Emitter.module.exports.Emitter.emit (C:\Users\Brwin\AppData\Local\atom\app-1.3.0-beta5\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Brwin\AppData\Local\atom\app-1.3.0-beta5\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1060:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\Brwin\AppData\Local\atom\app-1.3.0-beta5\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1030:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\Brwin\AppData\Local\atom\app-1.3.0-beta5\resources\app.asar\src\text-editor.js:588:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\Brwin\AppData\Local\atom\app-1.3.0-beta5\resources\app.asar\src\pane.js:534:18)
    at Object.module.exports.autosavePaneItem (C:\Users\Brwin\AppData\Local\atom\app-1.3.0-beta5\resources\app.asar\node_modules\autosave\lib\autosave.js:64:21)
    at C:\Users\Brwin\AppData\Local\atom\app-1.3.0-beta5\resources\app.asar\node_modules\autosave\lib\autosave.js:29:26
    at atom-pane.PaneElement.activeItemChanged (C:\Users\Brwin\AppData\Local\atom\app-1.3.0-beta5\resources\app.asar\src\pane-element.js:152:25)
    at Emitter.module.exports.Emitter.emit (C:\Users\Brwin\AppData\Local\atom\app-1.3.0-beta5\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\Brwin\AppData\Local\atom\app-1.3.0-beta5\resources\app.asar\src\pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\Brwin\AppData\Local\atom\app-1.3.0-beta5\resources\app.asar\src\pane.js:316:21)
    at atom-tabs.TabBarView.onMouseDown (C:\Users\Brwin\AppData\Local\atom\app-1.3.0-beta5\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:670:19)
```
### Commands

```
  6x -2:29.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:26 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:21.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:19.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -1:34.6.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
     -1:30.2.0 advanced-open-file:toggle (atom-text-editor.editor.is-focused)
     -1:25.3.0 core:backspace (atom-text-editor.path-input.editor.mini.is-focused)
     -1:24.6.0 core:confirm (atom-text-editor.path-input.editor.mini.is-focused)
  4x -1:20.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:17.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:17.2.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
  2x -1:16.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:14.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:14.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:07.2.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "advanced-open-file"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
advanced-open-file, v0.12.3
atom-beautify, v0.28.19
atom-jade, v0.3.0
atom-material-syntax, v0.2.4
atom-material-ui, v0.8.0
autocompile-jade, v0.0.1
autocomplete-html-entities, v0.1.0
color-picker, v2.0.13
emmet, v2.3.14
emmet-snippets-compatibility, v1.0.1
jade-autocompile, v0.6.5
jade-beautify, v0.0.11
linter, v1.11.2
linter-htmlhint, v0.2.1
linter-jade, v0.3.2
linter-sass-lint, v0.4.1
pigments, v0.19.0
sass-comment, v1.4.0
save-session, v0.15.7
snippets-jade, v0.1.1
space-tab, v0.4.2

# Dev
No dev packages
```

**Comment by manrueda** [comment]
Hi @Brwinded, you are working with a beta version of atom, can you confirm that this error still happens?

**Comment by jerone** [comment]
From time to time I'm getting the same issue thrown. I haven't been able to isolate it yet.

**Atom Version**: 1.3.2
**System**: Microsoft Windows 8.1 Pro
**Package**: [jade-autocompile](https://github.com/ManRueda/jade-autocompile), v0.6.5

**Comment by jerone** [comment]
Ah lol, just found the reason, it's while navigating to another tab while the package is still compiling. Probably the statusbar message isn't accessible on the switched tab.

Steps to reproduce:
1. Open any Jade file and compile it.
2. While compiling switch to another tab that _isn't Jade_.
